
import logging
import time
import sys
import pandas as pd
import os

from config import AppConfig
from services.taxonomy_service import TaxonomyService
from services.pubmed_service import PubMedService
#from services.semantic_scholar_service import SemanticScholarService
from services.kegg_service import KeggService
from services.uniprot_service import UniprotService
from services.fasta_service import FastaService
from services.subcellular_localization_service import SubcellularLocalizationService

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S" 
)
logger = logging.getLogger(__name__)


class CacheBuilder:
    """Class responsible for building and updating all local JSON caches for all datasets."""

    def __init__(self, email: str):
        self.email = email
        self.ncbi_delay = 0.35  
        self.uniprot_delay = 0.50 
        self.s2_delay = 3.0 
        
        try:
            self.kegg_service = KeggService()
            self.uniprot_service = UniprotService() 
            self.tax_service = TaxonomyService(email=self.email)
            self.pubmed_service = PubMedService(email=self.email)
            #self.s2_service = SemanticScholarService(email=self.email) 
            self.fasta_service = FastaService(tax_service=self.tax_service, email=self.email)
            self.subcellular_localization_service = SubcellularLocalizationService()
            
            logger.info("All services initialized successfully.")
        except Exception as e:
            logger.error(f"Initialization Error: Could not load services. Details: {e}")
            sys.exit(1)

    def _load_datasets(self) -> dict:
        """Loads all available datasets generated by data_manager.py."""

        datasets = {}
        
        files = {
            "enzymes": "data/enzymes_data.csv",
            "transporters": "data/transporters_data.csv"
        }
        
        for name, filepath in files.items():
            if os.path.exists(filepath):
                df = pd.read_csv(filepath)
                datasets[name] = df
                logger.info(f"Dataset loaded: '{filepath}' ({len(df)} records).")
            else:
                logger.warning(f"File not found: '{filepath}'. Skipping {name}.")
                datasets[name] = pd.DataFrame()
                
        return datasets

    @staticmethod
    def _deduplicate_articles(articles: list) -> list:
        seen_dois = set()
        seen_titles = set()
        unique_articles = []

        for art in articles:
            doi = art.get('doi')
            if doi:
                if doi in seen_dois: continue
                seen_dois.add(doi)
            
            title = art.get('title', '').strip().lower()
            if title in seen_titles: continue
            seen_titles.add(title)
            
            unique_articles.append(art)
            
        return unique_articles

    def update_taxonomy(self, datasets: dict) -> None:
        """Updates the Taxonomy cache for all species across all datasets."""

        logger.info("Initiating Taxonomy cache update...")
        
        all_species = set()
        for df in datasets.values():
            if not df.empty and 'Specie' in df.columns:
                all_species.update(df['Specie'].dropna().unique())
                
        added = 0
        for org in all_species:
            if org not in self.tax_service.cache:
                logger.info(f"Fetching Taxonomy data for: {org}")
                self.tax_service.fetch_taxonomy_lineage(org)
                added += 1
                time.sleep(self.ncbi_delay)
                
        logger.info(f"Taxonomy cache update completed. {added} new organisms added.")

    def update_kegg(self, datasets: dict) -> None:
        """Updates the KEGG cache for enzymes."""

        logger.info("Initiating KEGG cache update...")
        added = 0
        
        if not datasets.get("enzymes", pd.DataFrame()).empty:
            df = datasets["enzymes"]
            unique_enzymes = df[['Enzyme', 'EC number']].dropna().drop_duplicates()
            
            for _, row in unique_enzymes.iterrows():
                ec = row['EC number']
                if ec not in self.kegg_service.cache:
                    logger.info(f"Fetching KEGG data for EC: {ec}")
                    self.kegg_service.fetch_enzyme_details(row['Enzyme'], ec)
                    added += 1
                    
        logger.info(f"KEGG cache update completed. {added} new entries added.")

    def update_uniprot(self, datasets: dict) -> None: 
        """Updates the UniProt cache for all datasets dynamically."""
        
        logger.info("Initiating UniProt cache update...")
        added_general = 0
        
        for ds_name, df in datasets.items():
            if df.empty: continue
            
            item_col = "Enzyme" if ds_name == "enzymes" else "Transporter"
            id_col = "EC number" if ds_name == "enzymes" else "TC number"
            id_type = "EC" if ds_name == "enzymes" else "TC"
            
            unique_items = df[[item_col, id_col]].dropna().drop_duplicates()
            
            for _, row in unique_items.iterrows():
                identifier = row[id_col]
                name = row[item_col]
                
                clean_name = name.replace(' ', '_').replace('/', '_').replace('-', '_')
                cache_key = f"{id_type}_{identifier}_{clean_name}"
                
                if cache_key not in self.uniprot_service.cache:
                    logger.info(f"Fetching UniProt general data for {id_type}: {identifier}")
                    self.uniprot_service.fetch_protein_data(name, identifier, id_type=id_type)
                    added_general += 1
                    time.sleep(self.uniprot_delay) 
                
        logger.info(f"UniProt cache update completed. {added_general} general profiles added.")

    def update_literature(self, datasets: dict) -> None:
        """Updates the Literature cache (PubMed) for all datasets."""

        logger.info("Initiating Literature cache update (PubMed)...")
        added = 0
        
        for ds_name, df in datasets.items():
            if df.empty: continue
            
            item_col = "Enzyme" if ds_name == "enzymes" else "Transporter"
            id_col = "EC number" if ds_name == "enzymes" else "TC number"
            
            unique_combinations = df[['Specie', item_col, id_col]].dropna().drop_duplicates()
            
            for _, row in unique_combinations.iterrows():
                org = row['Specie']
                protein_name = row[item_col]
                identifier = row[id_col]
                cache_key = f"{org}|{protein_name}|{identifier}"
                
                if cache_key not in self.pubmed_service.cache:
                    logger.info(f"Searching Literature for: {org} + {protein_name}")
                    
                    pubmed_arts = self.pubmed_service.search_articles(
                        organism=org, 
                        protein_name=protein_name, 
                        identifier=identifier, 
                        keywords=AppConfig.PUBMED_KEYWORDS
                    )
                    
                    #s2_arts = []
                    #combined_arts = pubmed_arts + s2_arts
                    #unique_arts = self._deduplicate_articles(combined_arts)
                    
                    self.pubmed_service.cache[cache_key] = pubmed_arts
                    self.pubmed_service.save_cache()
                    
                    added += 1
                    time.sleep(self.s2_delay)
                
        logger.info(f"Literature cache update completed. {added} new searches added.")

    def run_all(self) -> None:
        """Executes the full cache building process."""

        logger.info("Starting full cache build process...")
        
        datasets = self._load_datasets()
        
        self.update_taxonomy(datasets)
        self.update_kegg(datasets)
        self.update_uniprot(datasets) 
        self.update_literature(datasets)
        
        logger.info("Initiating FASTA files generation...")
        self.fasta_service.process_all_datasets(datasets)
        
        logger.info("Initiating subcellular localization predictions...")
        self.subcellular_localization_service.run_all()
        
        logger.info("All caches updated successfully. Process completed.")


if __name__ == "__main__":
    USER_EMAIL = AppConfig.EMAIL
    
    builder = CacheBuilder(email=USER_EMAIL)
    builder.run_all()