
import logging
import time
import sys
import pandas as pd

from config import AppConfig
from services.taxonomy_service import TaxonomyService
from services.pubmed_service import PubMedService
from services.kegg_service import KeggService
from services.uniprot_service import UniprotService 


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S" 
)
logger = logging.getLogger(__name__)


class CacheBuilder:
    """Class responsible for building and updating all local JSON caches."""

    def __init__(self, email: str, data_filepath: str = "data/enzymes_data.csv"):
        self.email = email
        self.data_filepath = data_filepath
        self.ncbi_delay = 0.35  
        self.uniprot_delay = 0.50 
        
        try:
            self.kegg_service = KeggService()
            self.uniprot_service = UniprotService() 
            self.tax_service = TaxonomyService(email=self.email)
            self.pubmed_service = PubMedService(email=self.email)
            logger.info("All services initialized successfully.")
        except Exception as e:
            logger.error(f"Initialization Error: Could not load services. Details: {e}")
            sys.exit(1)

    def _load_dataset(self) -> pd.DataFrame:
        """Loads the dataset generated by data_manager.py."""

        try:
            df = pd.read_csv(self.data_filepath)
            logger.info(f"Dataset loaded successfully: '{self.data_filepath}' ({len(df)} records found).")
            return df
        except FileNotFoundError:
            logger.error(f"Critical Error: The data file '{self.data_filepath}' was not found.")
            sys.exit(1)

    def update_kegg(self, df: pd.DataFrame) -> None:
        """Updates the KEGG cache based on unique EC numbers."""

        logger.info("Initiating KEGG cache update...")
        unique_enzymes = df[['Enzyme', 'EC number']].drop_duplicates()
        added = 0
        
        for _, row in unique_enzymes.iterrows():
            ec = row['EC number']
            if ec not in self.kegg_service.cache:
                logger.info(f"Fetching KEGG data for EC: {ec}")
                self.kegg_service.fetch_enzyme_details(row['Enzyme'], ec)
                added += 1
                
        logger.info(f"KEGG cache update completed. {added} new entries added.")

    def update_uniprot(self, df: pd.DataFrame) -> None: 
        """Updates the UniProt cache based on unique EC numbers."""

        logger.info("Initiating UniProt cache update...")
        unique_enzymes = df[['Enzyme', 'EC number']].drop_duplicates()
        added = 0
        
        for _, row in unique_enzymes.iterrows():
            ec = row['EC number']
            if ec not in self.uniprot_service.cache:
                logger.info(f"Fetching UniProt data for EC: {ec}")
                self.uniprot_service.fetch_enzyme_data(row['Enzyme'], ec)
                added += 1
                time.sleep(self.uniprot_delay) 
                
        logger.info(f"UniProt cache update completed. {added} new entries added.")

    def update_taxonomy(self, df: pd.DataFrame) -> None:
        """Updates the Taxonomy cache based on unique organisms."""

        logger.info("Initiating Taxonomy cache update...")
        unique_organisms = df['Specie'].unique()
        added = 0
        
        for org in unique_organisms:
            if org not in self.tax_service.cache:
                logger.info(f"Fetching Taxonomy data for: {org}")
                self.tax_service.fetch_taxonomy_lineage(org)
                added += 1
                time.sleep(self.ncbi_delay)
                
        logger.info(f"Taxonomy cache update completed. {added} new organisms added.")

    def update_pubmed(self, df: pd.DataFrame) -> None:
        """Updates the PubMed cache based on unique organism + enzyme combinations."""

        logger.info("Initiating PubMed cache update...")
        unique_combinations = df[['Specie', 'Enzyme', 'EC number']].drop_duplicates()
        added = 0
        
        for _, row in unique_combinations.iterrows():
            org = row['Specie']
            enz = row['Enzyme']
            ec = row['EC number']
            cache_key = f"{org}|{enz}|{ec}"
            
            if cache_key not in self.pubmed_service.cache:
                logger.info(f"Searching PubMed for: {org} + {enz}")
                self.pubmed_service.search_articles(org, enz, ec)
                added += 1
                time.sleep(self.ncbi_delay)
                
        logger.info(f"PubMed cache update completed. {added} new searches added.")

    def run_all(self) -> None:
        """Executes the full cache building process."""

        logger.info("Starting full cache build process...")
        
        df = self._load_dataset()
        
        self.update_kegg(df)
        self.update_uniprot(df) 
        self.update_taxonomy(df)
        self.update_pubmed(df)
        
        logger.info("All caches updated successfully. Process completed.")


if __name__ == "__main__":
    USER_EMAIL = AppConfig.EMAIL
    
    builder = CacheBuilder(email=USER_EMAIL)
    builder.run_all()