
import os
import sys
import json
import glob
import logging
import subprocess

import pandas as pd

logger = logging.getLogger(__name__)


class SubcellularLocalizationService:
    """Service responsible for running subcellular localization predictions using DeepLoc 2.0 and DeepLocPro."""

    def __init__(self, data_dir="data", output_dir="data"):
        self.data_dir = data_dir
        self.output_dir = output_dir

        self.euk_fasta = os.path.join(self.data_dir, "euk_enzymes.fasta")
        self.pro_fasta = os.path.join(self.data_dir, "prok_enzymes.fasta")

        self.euk_csv = os.path.join(self.output_dir, "euk_enzymes_predictions.csv")
        self.pro_csv = os.path.join(self.output_dir, "prok_enzymes_predictions.csv")

        os.makedirs(self.output_dir, exist_ok=True)

    def _run_predictor(self, import_path: str, argv: list[str]) -> None:
        """Runs the specified predictor as a subprocess by importing its main function and passing the arguments."""

        script = f"""
import sys
from {import_path} import predict
sys.argv = {json.dumps(["prog"] + argv)}
predict()
"""
        subprocess.run([sys.executable, "-c", script], check=True)

    def _get_processed_ids(self, csv_path: str) -> set:
        """Reads the existing predictions CSV and returns a set of already processed IDs."""

        if not os.path.exists(csv_path):
            return set()

        try:
            df = pd.read_csv(csv_path, usecols=[0])
            if df.empty:
                return set()
            return set(df.iloc[:, 0].astype(str))
        except Exception as e:
            logger.warning(f"Could not read existing IDs from {csv_path}: {e}")
            return set()

    def _filter_fasta(self, input_fasta: str, temp_fasta: str, processed_ids: set) -> int:
        """Creates a temporary FASTA with only the sequences that haven't been predicted yet."""

        new_count = 0
        with open(input_fasta, "r") as f_in, open(temp_fasta, "w") as f_out:
            write_record = False
            for line in f_in:
                if line.startswith(">"):
                    full_id = line.split()[0][1:]
                    base_id = full_id.split(".")[0]

                    if full_id not in processed_ids and base_id not in processed_ids:
                        write_record = True
                        new_count += 1
                        f_out.write(line)
                    else:
                        write_record = False
                elif write_record:
                    f_out.write(line)

        return new_count

    def _get_result_files(self) -> set[str]:
        """Returns the current DeepLoc result files in the output directory."""

        return set(glob.glob(os.path.join(self.output_dir, "results_*.csv")))

    def _process_latest_result(self, target_csv: str, before_files: set[str] | None = None) -> bool:
        """Appends the newly generated predictions to the target CSV or creates it if it doesn't exist."""

        current_files = self._get_result_files()

        if before_files is not None:
            new_files = list(current_files - before_files)
        else:
            new_files = list(current_files)

        if not new_files:
            logger.error("No results file was generated by the model.")
            return False

        latest_file = max(new_files, key=os.path.getctime)

        try:
            if os.path.exists(target_csv):
                new_df = pd.read_csv(latest_file)
                if new_df.empty:
                    logger.error(f"Generated results file is empty: {os.path.basename(latest_file)}")
                    return False

                new_df.to_csv(target_csv, mode="a", header=False, index=False)
                logger.info(f"Appended {len(new_df)} new predictions to {os.path.basename(target_csv)}")
                os.remove(latest_file)
            else:
                os.rename(latest_file, target_csv)
                logger.info(f"Results file saved as: {os.path.basename(target_csv)}")

            return True
        except Exception as e:
            logger.error(f"Error processing results into {target_csv}: {e}")
            return False

    def predict_eukaryotes(self):
        """Runs DeepLoc 2.0 for eukaryotic sequences."""

        if not os.path.exists(self.euk_fasta) or os.path.getsize(self.euk_fasta) == 0:
            logger.warning(f"File {self.euk_fasta} does not exist or is empty. Skipping DeepLoc 2.0.")
            return

        processed_ids = self._get_processed_ids(self.euk_csv)
        temp_fasta = os.path.join(self.data_dir, "temp_euk.fasta")

        new_count = self._filter_fasta(self.euk_fasta, temp_fasta, processed_ids)

        if new_count == 0:
            logger.info("All eukaryotic sequences are already predicted. Skipping DeepLoc 2.0.")
            if os.path.exists(temp_fasta):
                os.remove(temp_fasta)
            return

        logger.info(f"Starting DeepLoc 2.0 predictions for {new_count} new eukaryotic sequences...")

        before_files = self._get_result_files()

        try:
            self._run_predictor(
                "ml.deeploc2.deeploc2",
                ["-f", temp_fasta, "-o", self.output_dir, "-m", "Fast", "-d", "cpu"]
            )

            ok = self._process_latest_result(self.euk_csv, before_files=before_files)
            if ok:
                logger.info("DeepLoc 2.0 predictions completed successfully!")
            else:
                logger.error("DeepLoc 2.0 finished without generating usable results.")
        except subprocess.CalledProcessError as e:
            logger.error(f"DeepLoc 2.0 subprocess failed: {e}")
        except Exception as e:
            logger.error(f"An error occurred while running DeepLoc 2.0: {e}")
        finally:
            if os.path.exists(temp_fasta):
                os.remove(temp_fasta)

    def predict_prokaryotes(self):
        """Runs DeepLocPro for prokaryotic sequences."""

        if not os.path.exists(self.pro_fasta) or os.path.getsize(self.pro_fasta) == 0:
            logger.warning(f"File {self.pro_fasta} does not exist or is empty. Skipping DeepLocPro.")
            return

        processed_ids = self._get_processed_ids(self.pro_csv)
        temp_fasta = os.path.join(self.data_dir, "temp_prok.fasta")

        new_count = self._filter_fasta(self.pro_fasta, temp_fasta, processed_ids)

        if new_count == 0:
            logger.info("All prokaryotic sequences are already predicted. Skipping DeepLocPro.")
            if os.path.exists(temp_fasta):
                os.remove(temp_fasta)
            return

        logger.info(f"Starting DeepLocPro predictions for {new_count} new prokaryotic sequences...")

        before_files = self._get_result_files()

        try:
            self._run_predictor(
                "ml.deeplocpro.deeplocpro",
                ["-f", temp_fasta, "-o", self.output_dir, "-d", "cpu", "-g", "any"]
            )

            ok = self._process_latest_result(self.pro_csv, before_files=before_files)
            if ok:
                logger.info("DeepLocPro predictions completed successfully!")
            else:
                logger.error("DeepLocPro finished without generating usable results.")
        except subprocess.CalledProcessError as e:
            logger.error(f"DeepLocPro subprocess failed: {e}")
        except Exception as e:
            logger.error(f"An error occurred while running DeepLocPro: {e}")
        finally:
            if os.path.exists(temp_fasta):
                os.remove(temp_fasta)

    def run_all(self):
        """Orchestrates the execution of both models."""

        logger.info("Starting subcellular localization prediction pipeline.")
        self.predict_eukaryotes()
        self.predict_prokaryotes()
        logger.info("Subcellular localization prediction pipeline finished.")