
import os
import streamlit as st
import pandas as pd
from config import AppConfig

def get_group_for_species(species: str, taxonomy_service) -> str:
    """Helper function to find which target taxa a species belongs to."""
    
    lineage = taxonomy_service.fetch_taxonomy_lineage(species)
    if isinstance(lineage, list):
        for node in lineage:
            if node.get("name") in AppConfig.TARGET_TAXA:
                return node.get("name")
        for node in lineage:
            if node.get("rank") == "class":
                return node.get("name")
    return "Other / Unknown"

@st.cache_data(show_spinner=False)
def load_all_localizations() -> pd.DataFrame:
    """Loads and combines all subcellular localization predictions generated by the localization prediction module."""

    dfs = []
    for ds in ["enzymes", "transporters"]:
        for dom in ["euk", "prok"]:
            path = os.path.join("data", f"{dom}_{ds}_predictions.csv")
            if os.path.exists(path):
                df = pd.read_csv(path)
                df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
                if 'Localizations' in df.columns: 
                    df = df.rename(columns={'Localizations': 'Localization'})
                if 'Protein_ID' in df.columns: 
                    df = df.rename(columns={'Protein_ID': 'Model_ID'})
                if 'ACC' in df.columns: 
                    df = df.rename(columns={'ACC': 'Model_ID'})
                
                if 'Model_ID' in df.columns and 'Localization' in df.columns:
                    dfs.append(df[['Model_ID', 'Localization']])
                    
    if dfs:
        combined = pd.concat(dfs, ignore_index=True)
        combined['Model_ID'] = combined['Model_ID'].astype(str).str.strip()
        return combined.drop_duplicates(subset=['Model_ID'])
        
    return pd.DataFrame(columns=['Model_ID', 'Localization'])

def _render_domain_view(df: pd.DataFrame, item_col: str, prefix: str, taxonomy_service):
    """Renders the UI for a specific functional domain (either enzymes or transporters)."""

    if df.empty:
        st.warning(f"No {item_col.lower()} data available.")
        return

    col_m1, col_m2, col_m3, col_m4 = st.columns(4)
    col_m1.metric("Species", df["Specie"].nunique())
    col_m2.metric(f"{item_col}s", df[item_col].nunique())
    
    if "Target sugar" in df.columns:
        col_m3.metric("Target sugars", df["Target sugar"].nunique())
    else:
        col_m3.metric("Target sugars", "N/A")
        
    col_m4.metric("Total records", len(df))
    st.divider()

    if "Class" not in df.columns:
        with st.spinner("Classifying species..."):
            unique_species = df["Specie"].dropna().unique()
            species_to_group = {sp: get_group_for_species(sp, taxonomy_service) for sp in unique_species}
            df["Class"] = df["Specie"].map(species_to_group)

    cols = df.columns.tolist()
    if "Class" in cols:
        cols.insert(cols.index("Specie") + 1, cols.pop(cols.index("Class")))
        df = df[cols]

    k_class = f"{prefix}_class"
    k_specie = f"{prefix}_specie"
    k_item = f"{prefix}_item"
    k_sugar = f"{prefix}_sugar"
    k_status = f"{prefix}_status"
    k_loc = f"{prefix}_loc"

    filter_keys = [k_class, k_specie, k_item, k_sugar, k_status, k_loc]
    for k in filter_keys:
        if k not in st.session_state:
            st.session_state[k] = []

    def clear_data_filters():
        for key in filter_keys:
            st.session_state[key] = []

    def get_filtered_df(exclude_col=None):
        temp_df = df.copy()
        if exclude_col != "Class" and st.session_state[k_class]:
            temp_df = temp_df[temp_df["Class"].isin(st.session_state[k_class])]
        if exclude_col != "Specie" and st.session_state[k_specie]:
            temp_df = temp_df[temp_df["Specie"].isin(st.session_state[k_specie])]
        if exclude_col != item_col and st.session_state[k_item]:
            temp_df = temp_df[temp_df[item_col].isin(st.session_state[k_item])]
        if exclude_col != "Target sugar" and "Target sugar" in df.columns and st.session_state[k_sugar]:
            temp_df = temp_df[temp_df["Target sugar"].isin(st.session_state[k_sugar])]
        if exclude_col != "Status" and "Status" in df.columns and st.session_state[k_status]:
            temp_df = temp_df[temp_df["Status"].isin(st.session_state[k_status])]
        if exclude_col != "Localization" and "Localization" in df.columns and st.session_state[k_loc]:
            temp_df = temp_df[temp_df["Localization"].isin(st.session_state[k_loc])]
        return temp_df

    def get_safe_options(col_name, state_key):
        if col_name not in df.columns: return []
        opts = get_filtered_df(col_name)[col_name].dropna().unique().tolist()
        for sel in st.session_state[state_key]:
            if sel not in opts:
                opts.append(sel)
        return opts
    
    col_title, col_btn = st.columns([4, 1])
    with col_title:
        st.markdown("### Filters")
    with col_btn:
        st.button("Clear filters", key=f"btn_clear_{prefix}", use_container_width=True, on_click=clear_data_filters)

    col1, col2, col3 = st.columns(3, gap="large")

    with col1:
        opts_class = get_safe_options("Class", k_class)
        groups = sorted([g for g in opts_class if g != "Other / Unknown"])
        if "Other / Unknown" in opts_class:
            groups.append("Other / Unknown")
        st.multiselect("Select class:", options=groups, placeholder="Select...", key=k_class)

    with col2:
        opts_specie = sorted(get_safe_options("Specie", k_specie))
        st.multiselect("Select species:", options=opts_specie, placeholder="Select...", key=k_specie)

    with col3:
        opts_item = sorted(get_safe_options(item_col, k_item))
        st.multiselect(f"Select {item_col.lower()}:", options=opts_item, placeholder="Select...", key=k_item)

    col4, col5, col6 = st.columns(3, gap="large")

    with col4:
        if "Target sugar" in df.columns:
            opts_sugar = sorted(get_safe_options("Target sugar", k_sugar))
            st.multiselect("Select target sugar:", options=opts_sugar, placeholder="Select...", key=k_sugar)
        else:
            st.multiselect("Select target sugar:", options=[], placeholder="N/A", disabled=True, key=f"{prefix}_sugar_disabled")

    with col5:
        if "Status" in df.columns:
            opts_status = sorted(get_safe_options("Status", k_status))
            st.multiselect("Select status:", options=opts_status, placeholder="Select...", key=k_status)
        else:
            st.multiselect("Select status:", options=[], placeholder="N/A", disabled=True, key=f"{prefix}_status_disabled")

    with col6:
        opts_loc = sorted(get_safe_options("Localization", k_loc))
        st.multiselect("Select subcellular localization:", options=opts_loc, placeholder="Select...", key=k_loc)

    filtered_df = get_filtered_df(exclude_col=None) 

    st.divider()
    st.success(f"Showing **{len(filtered_df)}** records based on your current filters.")

    display_df = filtered_df.copy()
    if "Source ID (NCBI)" in display_df.columns:
        display_df["NCBI_URL"] = "https://www.ncbi.nlm.nih.gov/protein/" + display_df["Source ID (NCBI)"].astype(str)

    st.markdown("<br>", unsafe_allow_html=True)
    
    col_config = {
        "Specie": st.column_config.TextColumn("Species", width="medium"),
        item_col: st.column_config.TextColumn(item_col, width="medium"),
        "Description": st.column_config.TextColumn("Description", width="large"),
        "Localization": st.column_config.TextColumn("Localization", width="medium"),
        "Source ID (NCBI)": None, 
        "NCBI_URL": st.column_config.LinkColumn(
            "Source ID (NCBI)", 
            display_text=r"https://www\.ncbi\.nlm\.nih\.gov/protein/(.*)" 
        )
    }

    final_cols = ["Class", "Specie", item_col]
    if "Description" in display_df.columns: final_cols.append("Description")
    if "Target sugar" in display_df.columns: final_cols.append("Target sugar")
    if "Localization" in display_df.columns: final_cols.append("Localization")
    if "NCBI_URL" in display_df.columns: final_cols.append("NCBI_URL")
    if "Status" in display_df.columns: final_cols.append("Status")

    st.dataframe(
        display_df[final_cols],
        use_container_width=True,
        hide_index=True,
        column_config=col_config
    )

def render_data_view(df_enzymes: pd.DataFrame, df_transporters: pd.DataFrame, taxonomy_service):
    """Renders the Data tab, splitting the UI into two domains: enzymes and transporters."""

    st.subheader("Explore the datasets of enzymes and transporters.")

    with st.spinner("Integrating subcellular localizations..."):
        df_locs = load_all_localizations()
        
        if not df_locs.empty:
            if "Source ID (NCBI)" in df_enzymes.columns:
                df_enzymes["Source ID (NCBI)"] = df_enzymes["Source ID (NCBI)"].astype(str).str.strip()
                df_enzymes = pd.merge(df_enzymes, df_locs, left_on="Source ID (NCBI)", right_on="Model_ID", how="left")
                df_enzymes["Localization"] = df_enzymes["Localization"].fillna("Pending")
                
            if "Source ID (NCBI)" in df_transporters.columns:
                df_transporters["Source ID (NCBI)"] = df_transporters["Source ID (NCBI)"].astype(str).str.strip()
                df_transporters = pd.merge(df_transporters, df_locs, left_on="Source ID (NCBI)", right_on="Model_ID", how="left")
                df_transporters["Localization"] = df_transporters["Localization"].fillna("Pending")

    tab_enz, tab_trans, tab_cross = st.tabs(["Enzymes", "Transporters", "Cross-analysis"])
    
    with tab_enz:
        _render_domain_view(df=df_enzymes, item_col="Enzyme", prefix="enz", taxonomy_service=taxonomy_service)
        
    with tab_trans:
        _render_domain_view(df=df_transporters, item_col="Transporter", prefix="tra", taxonomy_service=taxonomy_service)

    with tab_cross:
        st.markdown("### Metabolic pathway completion")
        st.markdown("Select a target sugar and see which species have both the enzymes to degrade it and the transporters to import the resulting sugars.")

        if "Target sugar" in df_enzymes.columns:
            enz_sugars = sorted(df_enzymes["Target sugar"].dropna().unique().tolist())
        else:
            enz_sugars = []

        if not enz_sugars:
            st.info("No enzyme target sugars found for cross-analysis.")
        else:
            selected_sugar = st.selectbox("Select initial substrate:", options=enz_sugars)

            if selected_sugar:
                metabolic_rules = {
                    "lactose": ["lactose", "glucose", "galactose", "glucose/fructose/galactose", "glucose/sucrose", "broad specificity"],
                    "sucrose": ["sucrose", "glucose", "fructose", "glucose/sucrose", "glucose/fructose/galactose", "broad specificity"],
                    "maltose": ["maltose", "glucose", "glucose/fructose/galactose", "glucose/sucrose", "broad specificity"],
                    "starch": ["maltose", "glucose", "glucose/fructose/galactose", "glucose/sucrose", "broad specificity"],
                    "cellulose": ["glucose", "glucose/fructose/galactose", "glucose/sucrose", "broad specificity"],
                    "glucose": ["glucose", "glucose/fructose/galactose", "glucose/sucrose", "broad specificity"],
                    "fructose": ["fructose", "glucose/fructose/galactose", "broad specificity"],
                    "galactose": ["galactose", "glucose/fructose/galactose", "broad specificity"]
                }

                valid_transporters = metabolic_rules.get(selected_sugar, [selected_sugar, "Unspecified", "broad specificity"])

                enz_match = df_enzymes[df_enzymes["Target sugar"] == selected_sugar].copy()
                tra_match = df_transporters[df_transporters["Target sugar"].isin(valid_transporters)].copy()

                species_enz = set(enz_match["Specie"])
                species_tra = set(tra_match["Specie"])
                ideal_species = species_enz.intersection(species_tra)

                if not ideal_species:
                    st.warning(f"No species found with a complete metabolic pathway to degrade and import **{selected_sugar}**.")
                else:                    
                    loc_col_enz = "Localization" if "Localization" in enz_match.columns else "Pending"
                    enz_clean = enz_match[enz_match["Specie"].isin(ideal_species)][
                        ["Specie", "Enzyme", "Source ID (NCBI)", loc_col_enz]
                    ].rename(columns={
                        "Source ID (NCBI)": "Enzyme ID",
                        loc_col_enz: "Enzyme Localization"
                    })

                    loc_col_tra = "Localization" if "Localization" in tra_match.columns else "Pending"
                    tra_clean = tra_match[tra_match["Specie"].isin(ideal_species)][
                        ["Specie", "Transporter", "Target sugar", "Source ID (NCBI)", loc_col_tra]
                    ].rename(columns={
                        "Source ID (NCBI)": "Transporter ID",
                        loc_col_tra: "Transporter Localization"
                    })

                    cross_df = pd.merge(enz_clean, tra_clean, on="Specie", how="inner")

                    with st.spinner("Classifying results for filters..."):
                        species_to_group = {sp: get_group_for_species(sp, taxonomy_service) for sp in ideal_species}
                        cross_df.insert(1, "Class", cross_df["Specie"].map(species_to_group))

                    st.divider()
                    
                    st.info("Note: for polisaccharides, look mostly for enzymes with predicted localization in **[Extracellular]** or **[Cell wall]**.")

                    st.markdown("#### Filter results")
                    
                    if "cross_f_class" not in st.session_state: st.session_state["cross_f_class"] = []
                    if "cross_f_specie" not in st.session_state: st.session_state["cross_f_specie"] = []
                    if "cross_f_enz_loc" not in st.session_state: st.session_state["cross_f_enz_loc"] = []
                    if "cross_f_tra_loc" not in st.session_state: st.session_state["cross_f_tra_loc"] = []

                    def get_cross_filtered_df(exclude_col=None):
                        temp_df = cross_df.copy()
                        if exclude_col != "Class" and st.session_state["cross_f_class"]:
                            temp_df = temp_df[temp_df["Class"].isin(st.session_state["cross_f_class"])]
                        if exclude_col != "Specie" and st.session_state["cross_f_specie"]:
                            temp_df = temp_df[temp_df["Specie"].isin(st.session_state["cross_f_specie"])]
                        if exclude_col != "Enzyme Localization" and st.session_state["cross_f_enz_loc"]:
                            temp_df = temp_df[temp_df["Enzyme Localization"].isin(st.session_state["cross_f_enz_loc"])]
                        if exclude_col != "Transporter Localization" and st.session_state["cross_f_tra_loc"]:
                            temp_df = temp_df[temp_df["Transporter Localization"].isin(st.session_state["cross_f_tra_loc"])]
                        return temp_df

                    def get_cross_safe_options(col_name, state_key):
                        opts = get_cross_filtered_df(col_name)[col_name].dropna().unique().tolist()
                        for sel in st.session_state[state_key]:
                            if sel not in opts:
                                opts.append(sel)
                        return opts

                    col_f1, col_f2 = st.columns(2, gap="large")

                    with col_f1:
                        opts_class = get_cross_safe_options("Class", "cross_f_class")
                        available_classes = sorted([c for c in opts_class if c != "Other / Unknown"])
                        if "Other / Unknown" in opts_class:
                            available_classes.append("Other / Unknown")
                        st.multiselect("Select class:", options=available_classes, placeholder="Select...", key="cross_f_class")

                    with col_f2:
                        opts_specie = sorted(get_cross_safe_options("Specie", "cross_f_specie"))
                        st.multiselect("Select species:", options=opts_specie, placeholder="Select...", key="cross_f_specie")

                    col_f3, col_f4 = st.columns(2, gap="large")

                    with col_f3:
                        opts_enz_loc = sorted(get_cross_safe_options("Enzyme Localization", "cross_f_enz_loc"))
                        st.multiselect("Enzyme localization:", options=opts_enz_loc, placeholder="Select...", key="cross_f_enz_loc")

                    with col_f4:
                        opts_tra_loc = sorted(get_cross_safe_options("Transporter Localization", "cross_f_tra_loc"))
                        st.multiselect("Transporter localization:", options=opts_tra_loc, placeholder="Select...", key="cross_f_tra_loc")

                    filtered_cross_df = get_cross_filtered_df(exclude_col=None)

                    st.markdown("<br>", unsafe_allow_html=True)
                    st.success(f"Showing **{len(filtered_cross_df)}** potential enzyme-transporter pairings based on your filters.")

                    display_cross_df = filtered_cross_df.copy()
                    display_cross_df["Enzyme_URL"] = "https://www.ncbi.nlm.nih.gov/protein/" + display_cross_df["Enzyme ID"].astype(str)
                    display_cross_df["Transporter_URL"] = "https://www.ncbi.nlm.nih.gov/protein/" + display_cross_df["Transporter ID"].astype(str)

                    st.dataframe(
                        display_cross_df[[
                            "Class", "Specie", 
                            "Enzyme", "Enzyme Localization", "Enzyme_URL",
                            "Transporter", "Target sugar", "Transporter Localization", "Transporter_URL"
                        ]],
                        use_container_width=True,
                        hide_index=True,
                        column_config={
                            "Specie": st.column_config.TextColumn("Species", width="medium"),
                            "Class": st.column_config.TextColumn("Class", width="small"),
                            "Enzyme": st.column_config.TextColumn("Enzyme", width="medium"),
                            "Enzyme Localization": st.column_config.TextColumn("Enzyme localization", width="small"),
                            "Enzyme_URL": st.column_config.LinkColumn(
                                "Enzyme ID (NCBI)", 
                                display_text=r"https://www\.ncbi\.nlm\.nih\.gov/protein/(.*)",
                                width="small"
                            ),
                            "Transporter": st.column_config.TextColumn("Transporter", width="medium"),
                            "Target sugar": st.column_config.TextColumn("Transported sugar", width="small"),
                            "Transporter Localization": st.column_config.TextColumn("Transporter localization", width="small"),
                            "Transporter_URL": st.column_config.LinkColumn(
                                "Transporter ID (NCBI)", 
                                display_text=r"https://www\.ncbi\.nlm\.nih\.gov/protein/(.*)",
                                width="small"
                            ),
                        }
                    )