
import os
import streamlit as st
import pandas as pd
from utils import add_taxonomic_class_column

@st.cache_data(show_spinner=False)
def load_all_localizations() -> pd.DataFrame:
    """Loads and combines all subcellular localization predictions generated by the localization prediction module."""

    dfs = []
    for ds in ["enzymes", "transporters"]:
        for dom in ["euk", "prok"]:
            path = os.path.join("data", f"{dom}_{ds}_predictions.csv")
            if os.path.exists(path):
                df = pd.read_csv(path)
                df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
                if 'Localizations' in df.columns: 
                    df = df.rename(columns={'Localizations': 'Localization'})
                if 'Protein_ID' in df.columns: 
                    df = df.rename(columns={'Protein_ID': 'Model_ID'})
                if 'ACC' in df.columns: 
                    df = df.rename(columns={'ACC': 'Model_ID'})
                
                if 'Model_ID' in df.columns and 'Localization' in df.columns:
                    dfs.append(df[['Model_ID', 'Localization']])
                    
    if dfs:
        combined = pd.concat(dfs, ignore_index=True)
        combined['Model_ID'] = combined['Model_ID'].astype(str).str.strip()
        return combined.drop_duplicates(subset=['Model_ID'])
        
    return pd.DataFrame(columns=['Model_ID', 'Localization'])

def _render_domain_view(df: pd.DataFrame, item_col: str, prefix: str, taxonomy_service):
    """Renders the UI for a specific functional domain (either enzymes or transporters)."""

    if df.empty:
        st.warning(f"No {item_col.lower()} data available.")
        return

    col_m1, col_m2, col_m3, col_m4 = st.columns(4)
    col_m1.metric("Species", df["Specie"].nunique())
    col_m2.metric(f"{item_col}s", df[item_col].nunique())
    
    if "Target sugar" in df.columns:
        col_m3.metric("Target sugars", df["Target sugar"].nunique())
    else:
        col_m3.metric("Target sugars", "N/A")
        
    col_m4.metric("Total records", len(df))
    st.divider()

    df = add_taxonomic_class_column(df, taxonomy_service)

    cols = df.columns.tolist()
    if "Class" in cols:
        cols.insert(cols.index("Specie") + 1, cols.pop(cols.index("Class")))
        df = df[cols]

    k_class = f"{prefix}_class"
    k_specie = f"{prefix}_specie"
    k_item = f"{prefix}_item"
    k_sugar = f"{prefix}_sugar"
    k_status = f"{prefix}_status"
    k_loc = f"{prefix}_loc"

    filter_keys = [k_class, k_specie, k_item, k_sugar, k_status, k_loc]
    for k in filter_keys:
        if k not in st.session_state:
            st.session_state[k] = []

    def clear_data_filters():
        for key in filter_keys:
            st.session_state[key] = []

    def get_filtered_df(exclude_col=None):
        temp_df = df.copy()
        if exclude_col != "Class" and st.session_state[k_class]:
            temp_df = temp_df[temp_df["Class"].isin(st.session_state[k_class])]
        if exclude_col != "Specie" and st.session_state[k_specie]:
            temp_df = temp_df[temp_df["Specie"].isin(st.session_state[k_specie])]
        if exclude_col != item_col and st.session_state[k_item]:
            temp_df = temp_df[temp_df[item_col].isin(st.session_state[k_item])]
        if exclude_col != "Target sugar" and "Target sugar" in df.columns and st.session_state[k_sugar]:
            temp_df = temp_df[temp_df["Target sugar"].isin(st.session_state[k_sugar])]
        if exclude_col != "Status" and "Status" in df.columns and st.session_state[k_status]:
            temp_df = temp_df[temp_df["Status"].isin(st.session_state[k_status])]
        if exclude_col != "Localization" and "Localization" in df.columns and st.session_state[k_loc]:
            temp_df = temp_df[temp_df["Localization"].isin(st.session_state[k_loc])]
        return temp_df

    def get_safe_options(col_name, state_key):
        if col_name not in df.columns: return []
        opts = get_filtered_df(col_name)[col_name].dropna().unique().tolist()
        for sel in st.session_state[state_key]:
            if sel not in opts:
                opts.append(sel)
        return opts
    
    col_title, col_btn = st.columns([4, 1])
    with col_title:
        st.markdown("### Filters")
    with col_btn:
        st.button("Clear filters", key=f"btn_clear_{prefix}", use_container_width=True, on_click=clear_data_filters)

    col1, col2, col3 = st.columns(3, gap="large")

    with col1:
        opts_class = get_safe_options("Class", k_class)
        groups = sorted([g for g in opts_class if g != "Other / Unknown"])
        if "Other / Unknown" in opts_class:
            groups.append("Other / Unknown")
        st.multiselect("Select taxonomic class:", options=groups, placeholder="Class...", key=k_class)

    with col2:
        opts_specie = sorted(get_safe_options("Specie", k_specie))
        st.multiselect("Select species:", options=opts_specie, placeholder="Species...", key=k_specie)

    with col3:
        opts_item = sorted(get_safe_options(item_col, k_item))
        st.multiselect(f"Select {item_col.lower()}:", options=opts_item, placeholder="...", key=k_item)

    col4, col5, col6 = st.columns(3, gap="large")

    with col4:
        if "Target sugar" in df.columns:
            opts_sugar = sorted(get_safe_options("Target sugar", k_sugar))
            st.multiselect("Select target sugar:", options=opts_sugar, placeholder="Target sugar...", key=k_sugar)
        else:
            st.multiselect("Select target sugar:", options=[], placeholder="N/A", disabled=True, key=f"{prefix}_sugar_disabled")

    with col5:
        if "Status" in df.columns:
            opts_status = sorted(get_safe_options("Status", k_status))
            st.multiselect("Select status:", options=opts_status, placeholder="Status...", key=k_status)
        else:
            st.multiselect("Select status:", options=[], placeholder="N/A", disabled=True, key=f"{prefix}_status_disabled")

    with col6:
        opts_loc = sorted(get_safe_options("Localization", k_loc))
        st.multiselect("Select subcellular localization:", options=opts_loc, placeholder="Subcellular localization...", key=k_loc)

    filtered_df = get_filtered_df(exclude_col=None) 

    st.divider()
    st.success(f"Showing **{len(filtered_df)}** records based on your current filters.")

    display_df = filtered_df.copy()
    if "Source ID (NCBI)" in display_df.columns:
        display_df["NCBI_URL"] = "https://www.ncbi.nlm.nih.gov/protein/" + display_df["Source ID (NCBI)"].astype(str)
    
    col_config = {
        "Specie": st.column_config.TextColumn("Species", width="medium"),
        item_col: st.column_config.TextColumn(item_col, width="medium"),
        "Description": st.column_config.TextColumn("Description", width="large"),
        "Localization": st.column_config.TextColumn("Localization", width="medium"),
        "Source ID (NCBI)": None, 
        "NCBI_URL": st.column_config.LinkColumn(
            "Source ID (NCBI)", 
            display_text=r"https://www\.ncbi\.nlm\.nih\.gov/protein/(.*)" 
        ),
        "Origin": st.column_config.TextColumn("Origin details", width="large"),
    }

    final_cols = ["Class", "Specie", item_col]
    if "Description" in display_df.columns: final_cols.append("Description")
    if "Target sugar" in display_df.columns: final_cols.append("Target sugar")
    if "Origin" in display_df.columns: final_cols.append("Origin")
    if "Localization" in display_df.columns: final_cols.append("Localization")
    if "Status" in display_df.columns: final_cols.append("Status")
    if "NCBI_URL" in display_df.columns: final_cols.append("NCBI_URL")

    st.caption("**Tip:** Double-click any cell to expand it.")

    st.dataframe(
        display_df[final_cols],
        use_container_width=True,
        hide_index=True,
        column_config=col_config
    )

def render_data_view(df_enzymes: pd.DataFrame, df_transporters: pd.DataFrame, taxonomy_service):
    """Renders the Data tab, splitting the UI into two domains: enzymes and transporters."""

    st.subheader("Explore the datasets of enzymes and transporters.")

    with st.spinner("Integrating subcellular localizations..."):
        df_locs = load_all_localizations()
        
        if not df_locs.empty:
            if "Source ID (NCBI)" in df_enzymes.columns:
                df_enzymes["Source ID (NCBI)"] = df_enzymes["Source ID (NCBI)"].astype(str).str.strip()
                df_enzymes = pd.merge(df_enzymes, df_locs, left_on="Source ID (NCBI)", right_on="Model_ID", how="left")
                df_enzymes["Localization"] = df_enzymes["Localization"].fillna("Pending")
                
            if "Source ID (NCBI)" in df_transporters.columns:
                df_transporters["Source ID (NCBI)"] = df_transporters["Source ID (NCBI)"].astype(str).str.strip()
                df_transporters = pd.merge(df_transporters, df_locs, left_on="Source ID (NCBI)", right_on="Model_ID", how="left")
                df_transporters["Localization"] = df_transporters["Localization"].fillna("Pending")

    tab_enz, tab_trans = st.tabs(["Enzymes", "Transporters"])
    
    with tab_enz:
        _render_domain_view(df=df_enzymes, item_col="Enzyme", prefix="enz", taxonomy_service=taxonomy_service)
        
    with tab_trans:
        _render_domain_view(df=df_transporters, item_col="Transporter", prefix="tra", taxonomy_service=taxonomy_service)